const BLOG_CATEGORIES = [
    "Technology",
    "Health",
    "Travel",
    "Finance",
    "Education",
    "Lifestyle",
    "Food",
    "Entertainment",
    "Sports",
    "science",
    "Art",
    "History",
    "Politics",
    "Environment",
    "Business",
    "Culture",
    "Fashion",
    "Photography",
    "DIY",
    "Parenting",
    "Other",
]

export {BLOG_CATEGORIES}